---
version: "3.8"
services:
  movies:
    image: sachinroutray22/moviespaytm:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: sachinroutray22/trainpaytm:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: sachinroutray22/rechargepaytm:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: sachinroutray22/dthpaytm:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
